displayName: OWASP CRS Modsecurity Plugin (nginx)
type: middleware

import: github.com/markkimsal/traefik-modsecurity-plugin

summary: 'Traefik plugin to proxy requests through owasp/modsecurity-crs. Keep-alive and passthru WAF failures.'

testData:
  ModsecurityUrl: http://waf:8080
  TimeoutMillis: 2000
  JailEnabled: false
  JailTimeDurationSecs: 600
  BadRequestsThresholdCount: 25
  BadRequestsThresholdPeriodSecs: 600

iconPath: ./img/icon.png
bannerPath: ./img/banner.png
